name: Test Some Assignment

on:
  push:
    branches: [ main ]
#     paths:
#       - './Questoes/'

env:
  BASE_FOLDER: ./Questoes/

jobs:
  Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_folder: [Q01, Q02, Q03, Q04, Q05, Q06, Q07, Q08, Q09, Q10, Q11, Q12, Q13, Q14, Q14v2, Q15, Q16, Q17, Q18, Q19]
        test: [1, 2, 3, 4, 5, 6, 7, 8]
        include:
          - test_folder: Q12
            test: 9
          - test_folder: Q13
            test: 9
          - test_folder: Q15
            test: 9
          - test_folder: Q15
            test: 10
        exclude:
          - test_folder: Q01
            test: 5
          - test_folder: Q01
            test: 6
          - test_folder: Q01
            test: 7
          - test_folder: Q01
            test: 8
          - test_folder: Q02
            test: 6
          - test_folder: Q02
            test: 7
          - test_folder: Q02
            test: 8
          - test_folder: Q05
            test: 5
          - test_folder: Q05
            test: 6
          - test_folder: Q05
            test: 7
          - test_folder: Q05
            test: 8
          - test_folder: Q06
            test: 5
          - test_folder: Q06
            test: 6
          - test_folder: Q06
            test: 7
          - test_folder: Q06
            test: 8
          - test_folder: Q07
            test: 6
          - test_folder: Q07
            test: 7
          - test_folder: Q07
            test: 8
          - test_folder: Q08
            test: 5
          - test_folder: Q08
            test: 6
          - test_folder: Q08
            test: 7
          - test_folder: Q08
            test: 8
          - test_folder: Q10
            test: 5
          - test_folder: Q10
            test: 6
          - test_folder: Q10
            test: 7
          - test_folder: Q10
            test: 8
          - test_folder: Q11
            test: 5
          - test_folder: Q11
            test: 6
          - test_folder: Q11
            test: 7
          - test_folder: Q11
            test: 8
          - test_folder: Q14
            test: 5
          - test_folder: Q14
            test: 6
          - test_folder: Q14
            test: 7
          - test_folder: Q14
            test: 8
          - test_folder: Q14v2
            test: 5
          - test_folder: Q14v2
            test: 6
          - test_folder: Q14v2
            test: 7
          - test_folder: Q14v2
            test: 8
          - test_folder: Q16
            test: 5
          - test_folder: Q16
            test: 6
          - test_folder: Q16
            test: 7
          - test_folder: Q16
            test: 8
          - test_folder: Q17
            test: 6
          - test_folder: Q17
            test: 7
          - test_folder: Q17
            test: 8

    steps:
    - uses: actions/checkout@v3
#     - uses: actions/checkout@v2.3.4
    - name: compile
      run: gcc -std=c11 -Wall -o a.out $BASE_FOLDER${{ matrix.test_folder }}/solution.c -lm

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: ./a.out < $BASE_FOLDER${{ matrix.test_folder }}/${{ matrix.test }}.in
        assert_file_path: $BASE_FOLDER${{ matrix.test_folder }}/${{ matrix.test }}.out
        expected_result: PASSED
