name: MyTester

on:
  push:
#     branches: [ main ]
    paths:
      - '.github/workflows/MyTester.yml'
      - 'Questoes/**'
      - 'MyTester*'
  pull_request:
#     branches: [ main ]
    paths:
      - '.github/workflows/MyTester.yml'
      - 'Questoes/**'
      - 'MyTester*'
permissions:
  contents: read

jobs:
  unix_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test with MyTester.py
      run: |
        python MyTester.py
    - name: Test with MyTester-v2.c
      run: |
        gcc -std=c11 -D_BSD_SOURCE -Wall -o MyTester.exe MyTester-v2.c
        ./MyTester.exe solution.c ./ ./Questoes/
        
