name: test.me

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/test.me.yml"
      - "example_input/**"
      - "Makefile"
      - "test.me.c"

  pull_request:
    #     branches: [ main ]
    paths:
      - ".github/workflows/test.me.yml"
      - "example_input/**"
      - "Makefile"
      - "test.me.c"

permissions:
  contents: read

jobs:
  unix_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Compile test.me.c
        run: make;

      - name: Run test.me with one folder.
        run: make run;

      - name: Run test.me with many subfolders.
        run: make run_folders;
