name: test.me

on:
#   push:
#     branches: [ main ]
#     paths:
#       - '.github/workflows/test.me.yml'
#       - 'example_input/**'
#       - 'test.me.c'
  pull_request:
#     branches: [ main ]
    paths:
      - '.github/workflows/test.me.yml'
      - 'example_input/**'
      - 'test.me.c'
permissions:
  contents: read

jobs:
  unix_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Compile test.me.c
      run: make; ls;
      
    - name: Run test.me with one file
      run: ./test.me ./example_input/Q01/solution.c ./example_input/Q01/tests/
      
    - name: Run test.me with many subfolders.
      run: ./test.me ./solution.c ./tests example_input/
        
