name: test.me

on:
  push:
#     branches: [ main ]
    paths:
      - '.github/workflows/test.me.yml'
      - 'example_input/**'
      - 'test.me.c'
  pull_request:
#     branches: [ main ]
    paths:
      - '.github/workflows/test.me.yml'
      - 'example_input/**'
      - 'test.me.c'
permissions:
  contents: read

jobs:
  unix_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Testing test.me.c
      run: |
        make
        ./test.me ./solution.c ./tests example_input/
        
